(defpackage #:aoc-test/day-11
  (:use #:cl #:lisp-unit2))
(in-package #:aoc-test/day-11)

(define-test test-day-11
    ()
  (multiple-value-bind (task-1)
      (aoc:run-day 11 "...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....")
    (assert= 374 task-1)))
